pdf2markdown:
  model: openai/gpt-5-mini
  temperature: 0.1
  ocr_model: mistral-ocr-latest

extraction:
  model:  openai/gpt-5-mini
  temperature: 0.1
  token_limit: 900000
  max_rounds: 12
  debug_logs_enabled: true
  clean_debug_logs_on_start: true
  debug_logs_full_response_once: true
  debug_logs_full_response: true

mapping:
  model:  openai/gpt-5-mini
  temperature: 0.1
