apiVersion: v1
kind: ConfigMap
metadata:
  name: pdf-converter-db-configmap
  namespace: default
data:
  DB_HOST: "dev-db-aurora.cluster-c5ipsfxjhb0m.us-east-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_USER: "urbind"
  DB_PASSWORD: "urbind"
  DB_NAME: "urbind"
  DB_URL: "postgresql+psycopg://urbind:urbind@dev-db-aurora.cluster-c5ipsfxjhb0m.us-east-1.rds.amazonaws.com:5432/urbind"
  DATABASE_URL: "postgresql+psycopg://urbind:urbind@dev-db-aurora.cluster-c5ipsfxjhb0m.us-east-1.rds.amazonaws.com:5432/urbind"
